GET http://localhost:8080/httptest/query?id=99
Accept: application/json

###
POST http://localhost:8080/httptest
Content-Type: application/json

{
  "name": "guang19",
  "age": 19,
  "lang": "CPP"
}



###
POST http://localhost:8080/httptest
Content-Type: application/json
Cookie: _octo=GH1.1.1155466184.1654778780; _device_id=127c8432fdc285af743147d545b14bf3; user_session=RrF2Hg4Ns-4PbSrGIZNiM_g77XA3eOZatP7IzrAh_Htnjhpa; __Host-user_session_same_site=RrF2Hg4Ns-4PbSrGIZNiM_g77XA3eOZatP7IzrAh_Htnjhpa; logged_in=yes; dotcom_user=guang19; has_recent_activity=1; color_mode={"color_mode":"auto","light_theme":{"name":"light","color_mode":"light"},"dark_theme":{"name":"dark","color_mode":"dark"}}; preferred_color_mode=light; tz=Asia/Shanghai; _gh_sess=nnXpheWD2Jj5LnmH2G8sm1IJhMhaFvq7afh++zwP3P5pEUJsIrN0RbBg8AINXqeby26fSR9oCyuZhw7ZFQXOorOoKII2aQh2jaAEo0g875MRs19Rw69iWuZtWkJ7nhVcavPGhxSROzg4YoQSc/dLOBW9B5savx1BKWBtsVx9m6AbFiIu+LRX9oEeA5c66thywq6OTpPkhpbkTTjWASmfq8suR1t5uciGAXju7kEX6uDO0G7OIgcEr8CCQaESKzX4Q2TlOCEdjoR8BrRIXtTbgdW0I0oGuwCyqCc7t0LuKTJ03Ly1QTGMRn5fJdg4x501goWIT9G6kgkXBPdiudHkytuBrUrdpYOz--BULuRSbFt6zu7kJQ--j6BXwhE6vAP8Dgqjo3J0jQ==

{
  "name": "guang19",
  "age": 19
}

###
GET http://localhost:8080/httptest
